on: push

name: Check SHAs

jobs:
  check_shas:
    name: Check SHAs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Ensure SHA Pinned Actions
        # You may pin to the exact commit or the version.
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@a397475397837fb57396bd18f09d991625e604fe
        # uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v1.1.1
